export default {
	// user settings
	GET_USER_SETTINGS: 'GET_USER_SETTINGS',
	GET_USER_SETTINGS_SUCCESS: 'GET_USER_SETTINGS_SUCCESS',
	GET_USER_SETTINGS_FAILED: 'GET_USER_SETTINGS_FAILED',
	UPDATE_USER_SETTINGS: 'UPDATE_USER_SETTINGS',
	UPDATE_USER_SETTINGS_SUCCESS: 'UPDATE_USER_SETTINGS_SUCCESS',
	UPDATE_USER_SETTINGS_FAILED: 'UPDATE_USER_SETTINGS_FAILED',
	LANGUAGE_CHANGED: 'LANGUAGE_CHANGED',
	// tutorial guide
	GO_BACK: 'GO_BACK',
	// notification
	HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
	SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
	// cat
	GET_CATEGORIES: 'GET_CATEGORIES',
	GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
	GET_CATEGORIES_FAIL: 'GET_CATEGORIES_FAIL',
};
